server:
  tomcat:
    uri-encoding: UTF-8
  port: 18081
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Ct981228
    hikari:
      # 连接池名
      pool-name: HikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间默认(600000)
      idle-timeout: 180000
      # 最大连接数量 默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间(默认半小时:1800000)
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000
      # 连接测试的sql语句
      connection-test-query: select 1
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间
        max-wait: 10000ms
        # 连接池最大空闲连接
        max-idle: 8
        # 连接池最小空闲连接
        min-idle: 1
    # 连接超时时间
    timeout: 10000ms

# mybatis-plus 配置

mybatis-plus:
  # 配置mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: cn.ha5fun.seckill.pojo

logging:
  level:
    cn.ha5fun.seckill.mapper: debug
